apiVersion: build.knative.dev/v1alpha1
kind: Build
metadata:
  name: kaniko-build-v2
spec:
  nodeSelector:
    type: vps
  serviceAccountName: build-bot
  source:
    git:
      url: https://github.com/sfxworks/knative-demo
      revision: master
  template:
    name: kaniko
    arguments:
    - name: IMAGE
      value: docker.io/quantomworks/knative-demo:v2
